on: [push]

name: AzureLoginSample

jobs:

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_SP_CREDENTIALS }}
    
    - run: |
        az webapp list --query "[?state=='Running']"
